# Generated by Django 4.1.5 on 2024-01-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Category',
            new_name='Item_Category',
        ),
    ]
