# Generated by Django 4.1.5 on 2024-01-31 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_category_listings_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
